version: "3.3"

networks:
  main:
    driver: bridge

services:
  #contenedor web de la aplicación donde ejecutamos la aplicación como tal
  mytomcat:
    image: tomcat:latest
    container_name: tomcat-imagen
    hostname: tomcat
    volumes:
      - ./target/Estudio33WebApp-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/estudio33.war
    ports:
      - "8080:8080"
    networks:
      main:
  #base de datos de postgres
  mypostgres:
    image: postgres:latest
    container_name: postgres-imagen
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./database-docker/init.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      main:
  #servidor web donde se pueden hacer peticiones ajax
  myhttpserver:
    image: httpd:latest
    container_name: httpserver-image
    hostname: httpserver
    volumes:
    - ./ajax-files/:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
    networks:
      main:
